### ISSUE TITLE
Master node not needed when click add worker node

### ISSUE THREAD

**Issue by pakkua80** [dsieradzki/k4prox#27]
Hi, my workflow as below

1. I wanted to add additional worker node. 
2. I do not want extra master
3. I know my master add node key ( microk8s.addnode )
4. I am thinking of using k4prox to add additional workers node
5. delete all default master
6. click add worker node ( ERROR : Didn't expect it to auto add master node )

![image](https://user-images.githubusercontent.com/2527115/196657420-6659c020-0b7c-439c-a82d-20fb2137be5b.png)

**Comment by dsieradzki** [comment]
As I mentioned in https://github.com/dsieradzki/k4prox/issues/28, currently post installation management is not supported, but this is my next feature that I want to implement.
