### ISSUE TITLE
should not get kubernetes config for master

### ISSUE THREAD

**Issue by pakkua80** [dsieradzki/k4prox#28]
Hi,

        My intention here is to add a "orphan" worker node to join the cluster on my own since the wizard steps do not allow a workflow to add additional worker node.

![image](https://user-images.githubusercontent.com/2527115/196658321-c282b629-a107-462d-bd38-bd11072c9b33.png)

![image](https://user-images.githubusercontent.com/2527115/196658414-350282b7-ed8d-4c41-b60b-64f6e12ee14c.png)

![image](https://user-images.githubusercontent.com/2527115/196661923-b9e67773-34d2-48d2-870d-3246562306fd.png)

Unless you tell me there is a proper workflow to do what I intend to do : is to add additional worker node into the cluster.

**Comment by dsieradzki** [comment]
Currently there is no possibility do add worker node to existing cluster. Wizard always creates cluster from scratch. Post installation management I want to cover in separate feature, where you will be able to add or remote nodes from cluster.

**Comment by pakkua80** [comment]
👍 do you need a PM for your project or a QA ? Btw, I was the person on LinkedIn that tries to connect with you. Lee here

**Comment by dsieradzki** [comment]
I have created feature issue for adding nodes to existing cluster https://github.com/dsieradzki/k4prox/issues/36
