### ISSUE TITLE
one master not get ready

### ISSUE THREAD

**Issue by scrhall** [dsieradzki/k4prox#32]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/5793824/201083556-90518107-af78-4edd-bd18-edd247ee2bb6.png">
how can debug the master node?

**Comment by dsieradzki** [comment]
From application perspective, currently there is no such of possibility. App bases what `kubectl get nodes` returns. You have to go to your master node and check manually. I observe that MicroK8S have very long responses after install on low performent disks.

**Comment by dsieradzki** [comment]
Cannot reproduce
