### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by namm86** [dsieradzki/k4prox#50]
Getting this error while executing `wails build`:

go version go1.18.1 linux/amd64
Wails CLI v2.2.0

A Type: 		desktop
Platforms: 		linux/amd64
Compiler: 		/usr/bin/go
Skip Bindings: 		false
Build Mode: 		Production
Frontend Directory: 	/home/nico/Documents/k8/k4prox/frontend
Obfuscated: 		false
Skip Frontend: 		false
Compress: 		false
Package: 		true
Clean Bin Dir: 		false
LDFlags: 		""
Tags: 			[]
Race Detector: 		false

Building target: linux/amd64

  - Generating bindings: Done.
  - Installing frontend dependencies: Done.
  - Compiling frontend:     
    > frontend@0.10.0 build
    > tsc && vite build
    
    file:///home/nico/Documents/k8/k4prox/frontend/node_modules/vite/bin/vite.js:7
        await import('source-map-support').then((r) => r.default.install())
        ^^^^^
    
    SyntaxError: Unexpected reserved word
        at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
        at async link (internal/modules/esm/module_job.js:42:21)
    
Error: exit status 1
ERROR: exit status 1

**Comment by dsieradzki** [comment]
It's look like dev environment issue rather than app itself.
Check Node.js version, it should be latest LTS(v18.12.1). 
Clear node_modules, also ensure that you have Wails v2.2.0
