### ISSUE TITLE
Helm Repo already there

### ISSUE THREAD

**Issue by bitbucket90** [dsieradzki/k4prox#56]
Tried to deploy k8s-dashboard, failed. 

Went to manually do it and realized it needed to be tagged correctly, deleted and created nearly the same helm app.

Error is stating repo already exists. 

I know how to clear this in CLI, however seems like a user facing bug. 

For those in need

`helm repo remove `

**Comment by dsieradzki** [comment]
Hello, thank you for reporting the issue. I will create the fix shortly.

**Comment by dsieradzki** [comment]
Unfortunately I cannot reproduce this behavior. Even repository is added already this should not cause error during chart install. Helm returns success error code(0) when repository is already added, so K4P doesn't have reason to stop operation of installing Chart
  `helm repo add nginx-stable https://helm.nginx.com/stable
  "nginx-stable" already exists with the same configuration, skipping
  damian@sieradzki:~$ echo $?
  `
  I think that reason of error is different, can you provide logs?
