### ISSUE TITLE
helm example

### ISSUE THREAD

**Issue by enieber** [dsieradzki/k4prox#82]
Hi, I like much this project but no has sucess to use app with helm, if has some example how to use helm is very nice.

**Comment by dsieradzki** [comment]
Hi, you can install Helm Chart during provisioning or later. Simply add Chart data, click Save and Install. 
Example with ingress:
![after](https://github.com/dsieradzki/makoon/assets/10297559/804f66af-359a-4f3e-907f-3b37357442d7)
